--1. Easy Find all sales transactions where more than 5 units of a product were sold.

select * from sales
where quantity > 5

--2.	Easy Find the total quantity of products sold for each Product_ID.
select product_id, sum(quanyity) as [total quantity]
from sales 
group by product_id

--3.Medium	Calculate the total revenue generated by each DMart store.  
select store_id,sa.store_name,sa.store_city (sa.selling_price * sa.quantity) as Revenue
from store s join sales sa
on s.store_id = sa.store_id
group by sa.store_id,sa.store_name,sa.store_city

--4.Medium Calculate the total revenue generated by each product category. 
select p.category,(sa.selling_price * sa.quantity) Revenue
from products p left join sales sa
on p.product_id = sa.product_id
group by p.category

--5.find all products that belong to the grocery category
select * from products 
where category = 'grocery'